### PR TITLE
Support for MongoDB 3.4

### PR DESCRIPTION
**Pull request by janat08**
I didn't detect any variance related to mongo versions within init files.

### CODE REVIEW

**Comment by janat08** [comment]
#1

**Comment by mitar** [comment]
Did you build the Docker image and try it out? Does it work with Meteor app?

Do not copy the init files, but use the same directory twice. Maybe rename it from `etc-2.6` into `etc` only or something.

**Comment by janat08** [comment]
fine, let me see if i can see if docker image is working.

**Review by mitar — CHANGES_REQUESTED** [review]
Please address comments I made previously.

**Comment by janat08** [comment]
Don't know if it works, I can't run hello-world to start with.

**Comment by mitar** [comment]
No, 2.4 needs a special init script, but 2.6 and 3.4 probably share them.

You should really test this. Untested pull requests done by guessing are not really helpful. Most time is not spend in making a change, but in making sure the change works as expected.

**Comment by janat08** [comment]
Don't know what constitutes it working, local collection:
me
oplog.rs
replset.election
replset.minvalid
startup_log
system.replset
...
        "name" : "wiredTiger",
        "supportsCommittedReads" : true,
        "readOnly" : false,
        "persistent" : true

**Comment by mitar** [comment]
Thanks!

**Review by mitar — APPROVED** [review]

**Pull request merged**
